image:
  repository: registry.atlas.lan/atlas-admin/docs
  tag: sha-de0f8047106b5d035af3fca8684031a8f9b10c19-run-129-1
  digest: sha256:6f511911e1834cd74a8a81164426d780314f0566b3ed852a0646a01c1f32aa20
  pullPolicy: IfNotPresent

imagePullSecrets: gitea-registry

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  className: traefik
  host: docs.atlas.lan
  annotations:
    cert-manager.io/cluster-issuer: atlas-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tlsSecretName: docs-tls

resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
