image:
  repository: registry.atlas.lan/atlas-admin/docs
  tag: sha-56616049c1be8486132e2f7dd5da996b8479c49f-run-121-1
  digest: sha256:49f39ea2ba6eacfabcffabcb2373730ef6b3ed402a5e60bc2ddc2427a15129b4
  pullPolicy: IfNotPresent

imagePullSecrets: gitea-registry

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  className: traefik
  host: docs.atlas.lan
  annotations:
    cert-manager.io/cluster-issuer: atlas-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tlsSecretName: docs-tls

resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
