image:
  repository: registry.atlas.lan/atlas-admin/docs
  tag: sha-f42dd2a7d6288f89a8dc12e2906e190f0b2f368e-run-95-1
  digest: sha256:d0631090e2f7180f59934f118bb4f5fa8e74c95fad90564e68c621f2abcc2bd4
  pullPolicy: IfNotPresent

imagePullSecrets: gitea-registry

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  className: traefik
  host: docs.atlas.lan
  annotations:
    cert-manager.io/cluster-issuer: atlas-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tlsSecretName: docs-tls

resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
