---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: demo
spec:
  encryptedData:
    .dockerconfigjson: AgCC8sxUSWA8oigEv2l3GEie+rrko93TOn6YyYMkGuPgXlmzMhrXOZlglKFle7FHK/2ywf8TwEppdujJeolnu4t76w/RMN7Htkr39JCfTibA2eUP2xNCbcc7l20ENEepn7bcgAwGeAexlnpNW/1Qa5mcycf6/iI5bHvy4pYgd+/j0Fimz/o01pSPEGgn0U688G/8XbynOQHjgQwSSm1FPz+FcQ0PnW47EWGRp+jdQ/a5MOA9z78ETpDz/DaKw03S7+vp6q3nakjlyLqDwb7KHuM+A5UjuyEjPFVPPfDvqBAPNrlEJ1N820nIQoVo6kBIooPKCIvQDqcLwPVymrFcKWPbFDe4qcKOfH1WRyenTaU/u8y91lU2XvZ5AZgSgiwcnqFfoVfcwGaJhmTLTZXDPYyJTdl8+n0V0qEjWY5lXTm/x+rcrvGGwS6888t+qomaokgeKhjYQtD7jmwqWzyg+bGQm4b4QsnAU7lv4E4LDBdUtp08LnDR0nUqD4ceISAq8LxMYIg56MQVWWJyWH199QufE5RPl1qjfpP5xpeiAz2ghxFK5V8gYImY25FZoIS9nihNSPNDIdsAXsFaSpfmY6kd6jKpvvrXLNTe3uoL9QMmqgIcmbT045J8jzzr1KBwLmpKAdnJ6MfaI76qbYbu5PrGYEtJuqzY+AOcRMc7KJ2mLQQ8fB8+u17JLn4UvS97f3b5K2N2ZYgxt4VSI7UpaIRZYsYvx7e8jhaua+dLqSNrRYTyJDwMQm0KKtte0Rx2hGrjVT4khQLy3tpB3EZoztuj/D1Qf5pdierI/Pc6Reh+AkF7Vqa2tkl+oHpycUm+XZP9MQX87+ubz9ZcRfKYFZD2gL7cYAfNTyEz3ZdB1H9uuu1CBFfchVUs4GJULBQ=
  template:
    metadata:
      name: gitea-registry
      namespace: demo
    type: kubernetes.io/dockerconfigjson
