---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-writeback
  namespace: argocd
spec:
  encryptedData:
    password: AgCZl8r33qm5QGqp2A9x9aiXk7gUc6TIA5Y1Fa2dIehnITnHscjN+RG2j7I6+gjEyoTup7RRDjmuHmGlFPGwbefhq5kwDrKWWJACiTOOE5tnYYQbhiLUs3YWJsOfU9UvHIL87zR4U26G11JhTS4xg6dVAw6h34ALeL0e1EV+YIKcdIbC+gkHAbeuB23rRV5x0ZapxYBk3ZCIDIHl+Qd+C318q0QG/XNEjjG8xV7p/b32oru75YvzOcEl92eA5WJnaj+3n7rsRAeHD0eYuezfX0sM1mFxaIhJnb94pYbR6JNB6bci9dYigOb574zJVniKLAPkZTESQmRLud7H3j7bXdPrvqg0TQImkiU6OaJzT4pwMa56F/62hdGLiwcKXYN7l9x9bbTJCYsn7HcGbLjlw3dKOMGxwN46m4BPKwl2GMvuwA1vxm3AUqBrvb53L/T79xIshLZJ0QHUcB3pDEvsAuQp7ecfCz1+Oz1/ZbyOi8fOIQ7kj21UBZwMjwh43+pELm9lYvoZWGq7TGC2mmLm10KCvafxWmloEN12AvZY4775QfKMgl45oXMc/FHJ/hCOWXhrptV3sBt6KT4K12LGuU0U3VxzAI+nEmCRjopEHvcgYjgtwsOKFH/jfacGtCWybylG6mdB2XIfVPXhTaJRW109Txhl2mb6iMxMQ9pd9NGemJNNHeQ8oRJM67MKnvAJVDmy/yu4muED8+jl8veXm8jtQmmhQVDfY1bJ9cDvEvoFSSLvk/MRe/vq
    username: AgCvcDcOQPoixCltX3YW7/oI0n0jljIuxsH6KOIU/zzuqa+WNHfrW8Uwf7UjRUJrDBiSo2UDX+2X2ysXB8fe3HGo5Ksv7eWeiJzAzYaJmXMcEhT86EdyJXWww7w/wkj40BugRcB/4qKBRyC6urDEabYN8V0HxzyLlf+re2xhy6on7EoRZLTwAAWWN64ju7MGj5o36KMFSkDf/rZJyzYbdU6W0KXfDwsQJAZgQLLawBB2ouq5t5aJC5uQm1b/EBHoxH2u9g7c4oJ8B2gHEbJ/NaTu3+WpL2IVaVz37aXkGhzIOrCklk+4xNvPZ6xj2ISyUKv01bejbXM5epQFBVc+a2ARRhL/4tFdYi2ip6xGS/tWY3L/uP4cEpW0ENo2dWjaRmCb7p345JljoIJtWA5fLQjz9FvbbJIis6apGMMjTLDwEulsT4KQqfKny5twXejdquUvlifMfCuUoZhWbD9qYUqiGTOEm8nYadsMqadX2rgaNn9nGM+IkgeqsknvD+/unRxI/28w6XCt8UXZC+EaCnDoXPBn1i3xojE2/cfwIhjzcY36EM4PlIpTsjRpJVvRtpXrNV+SPN+M6z+h0pHKEagLEfKRMApRKshrxsXOm1JswYs8r/WQET4BwcY8whVOu87/0nlYsppdIgVA4e0Rr6RIxzrK3Q0WrrJwVfseAWzdn7mR3evIByknmqsXntDMRETkc6eo9u+5jgmDIg==
  template:
    metadata:
      name: gitea-writeback
      namespace: argocd
    type: Opaque
