---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  encryptedData:
    password: AgBuxmze7xJF6cM+9zzkeBAND2Z/oRR8mJb4vR5TjF8epAvDYHFG4wmW6i3w06LNPS0jaec/vMMGb/7cHthdSLhlsr+1WwfAK5xqaIEiRdXBQVRsNh1dZAQdL3eeCzAJm/h+g8KNzdI6lQnPT2+JlypQr3DKGvCtjzLjGrV66RAr8b9w03zbWf3dXjz3erA/ansxI0RULR/JSleAuvBziQqCN9QWnw8tCrbV8zL+9VuOBAY/lTridoAgMfS50+CTqzgUQFRrsK/xTI1Q8+7CpWn5uJ/FcCyCy56X1+Dy+yRMnCUfvNBhAxk7VdLrzc2oUDMrML+1NlQv6Og2TU+ntQKMtzVf1PccqWePPbt74sy/3g2zIwMQEDonGZbI8oV0f2jEENSdWReC79sy7HxMZuXY0StEmac2VziiJxcuLR9r6aJGvIKQPZw832hmv2atbXDYJTvdfNDZ6bxi0XcofPAFMtrV9TrGK34hLUfI2uENClNVdZl+TITAC1G+wyBn/gDirySicuSnW5gb6vl+P5OZkxU/haGxJWCDTL9B/7+BCsGOZwlQFWacaVi3jSsy/plV8M4i/ER0l9uGpOn/hVMO0WNjVhuxvQVnsGB/58hl898labXwzP86f4gguKPppl0c3SfKlTbanq9+9xMRPF3nYVsSUnjWxv94gQ1MDYgs7kFKs3eqhCYUbrDqhypz0VXjGQxyoqcxbwPhCxLMGWN0PBwo1X3gDxdCR5ZN8n1XMw==
    postgres-password: AgBSlSaEKq0BLI3abEIoJNoCdS1jdh0RYK9vbklR4wT0i8E4ZSf87lufxHEE+vXp6xeMW9YFpTN8lu5jc2Cv+trgufCX7lBa7Issjlhj4AqFktjDQthVkoKZ72vIpRBs7EKOUxo1wsFZXA0BFaSWHmi1ib6z45fRlQYyYwV4gk+Cxx0LGQPudsfswwivE+vcz6vGE7nfFIKNnHqEMfZLWkHKAP5J5lO+P9FihbjaLVlL/ek93bKDKqnssdZwJedwZY5uoupSNkZM6Zh/RF2GLBuZtCFWVxjboq0upwZiX/2MRf1lP7xY6/edoe5iddLYvj3D37+y9iNHj7zsfV1dVC0ujBQJ32q9+XDuohFcmj2QPwscmWi3zmbziu7JSbXfflN6lCtJLysC+nQEzyV8/iUAzSDuzWfEA2h68ZbpZfYMgnKtr6rokB/Zujc6KxSOwwWCqKTzFIjIEDsei7g+Gc8J5kBEw2j+pvXb/Rtij4rMaIG5WF9M1tJ+aJ+IGk528/hBcH1Bi8E7rgv9wKk1xGVdRPrXZ3jccDxal9kiyZvaV3mMHaHc0MfkNwzgnj6mS2w9q+aKZN2HkU++LCq1jybyQPrfhemKBeKOM7VYKRH2sftUh/R/tjE+GQ+VcIkEZGCbt1NxSYCYSH8QdjgsFaVxjKEbikOgvb53g9FfB6fkgxu2X3DQHKvck3fRYlDQIKxZVdYvtZc6rsRoKp9m2FR+Cd8EYXaHJzXV+ODmjCzG7Q==
  template:
    metadata:
      name: gitea-postgresql
      namespace: gitea
    type: Opaque
