---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-token
  namespace: gitea
spec:
  encryptedData:
    token: AgAOGWPM24MjXdW5pQx4n8+25Wo2pnYvSyWHEbZ1WupJWgzcD6Zyoej3ifdwaECqDQPTwsTnDh68oMRzwKZxEiMyeOIn9fR2hsuUt0Slpe8cR5KRS3onXFXWrKveGFBZ1A81VCHlT9SvMbxelUSZkNZ6ll483ysHQxEoXpIYqxw76Uqk2TK1dCRpfFhwpkK5tQDXMeZvsFI2oDGV1Lqa6MRdCDQKUciepeeHnd9UzH2qWn58BEtI3yyK3/rSWldrGgbls6jMYOuSWBCT5MIAcfFpEPIR8QVoeaZrzWf1EiZkWlVfR6lmG5hnv3O/daKrN8e3wwGQYEzFhtoBOyNWC/ZQa0EyII7vCEq1XhLB+1+MXECXIpcQWN6v8wnc1TgNgsBLx48PyxgAkLmcEXTpnglagl0ET+tsOGQrT2AAKiJNOIDNHi+zncJM/BW6CXlu9H0NR9o+8+lPyamnS73jS0SS4JqDsFYdToLAKAh29kPnZYw8c7kXug+FuJwzLG+7IjXPPyFnqvWDlXvqypBoyFQqfqE7UMPo1YYX6IKglC9z/XNOLyGfXbKSOOpuxJ42YYmVTjnj57oAL9mh6Jh5DIkPCQ5OA5MIwmwrmaTYx3VQVmMbnmLVNcp3bNNrdYR6oWG9vomX3HL57IKCpLvQgXr2L2PIHqchPr5OiqttFZLv2NitXK3VorpBcC8w/Cq96GqUuk4UYvz2ZvCEoBvDMx/4xrIxyBd4BcUVMMe/p//AkT52Y+nnubZX
  template:
    metadata:
      name: gitea-runner-token
      namespace: gitea
    type: Opaque
