---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-writeback
  namespace: argocd
spec:
  encryptedData:
    password: AgALz+JiqMxaO8GNxOxxw5I9U+bhaZXDkMKSOe90RjUVAeyE50OdaKkjYMvdOw5nMiWEy1tTLP8aAdLsu8mIkDIt/qZmT0sYLEDfYHvI9aurrmg45cuNwPgILcoxtAR3Vg2XemrkTRbfpNgnjnH9Z+o6DFmISg6dOJCjYQXgssPnQJzKBayDq5t3cAq0Lt2c5BHFaMmczjrV/rQl2/QF7s0PGcxA0sjLDubHwy0BNM2G3xLfXKpMatgvHYHOQXatKBWYjYi2zX3WaI/xIc+7KPvYyxarP7rjgSwE8g+lqBg53nvDgdvhs32U703Efbm3z1WB8RXdnbR+tw9rgTGFck1XvB40tRu/B7a74tb+YDD+IA/NRmffFgkvcMvKB6XGyMLG/XHGJe/nXoxuPR96xp12oahh6Lm/kpEBbNSvv8XMCbY2GBa5eREEOQSzES1ltrMPZPPDIsVIGtF2EV6bJ9nQ5xQ0ejeUBUtbf2jpiabz+GWk7+nu9XEVmTpjpGBOrNJkvN70gkt3AuV+I/TD3aDuC9eQuHOAw54op3gDwU7oofSVfgrURwGWRuMEdA9DsS8tbnNMFHxtZHYXLhi+nUyrCjSn5wbD54YQhsth42s/OUsE8D5zlz2HTUm6Q3u1zaELF0HvrxIYAbFPqXzLJUQZ39vRQsx1I4oAdUYpmZ0I7rcDByXOQlvZbuOco0GyM52dybeUHBjIq11pJ3zF6Ms+moOnPApnkpfvyGgreMZxOf+YIFxtZB6I
    username: AgCp6crCMxA6KsudWSY61nqyWtTtok3KDhJ+V88h8lOHM4X6LgPizK1bn3wNhh+r3/iEE/UgJ3zmCrcW13ChpkIlilof3SKfaOG/z8XmPINbN9kKKfXRrw9o3SYCcZRuqZHNZB3KS6fGIjZFUie7ZLZL7bux6O6FKLFb2qqifqtiEFSavsjRzChad1NyUI0lSl7jM4GT8HN6300kBCtvjQVKLo5iGRskNfgueIHfiAb9SbU8uqgPlNZjmBAlxzPK6UuAnuBa6zqCoDMRDrE0p/+pBJCGgLaYx3wXCQ6Vx6VD7lhMZJOFLrzTo3DJKQKXhS+JMaQhPT49STLXBU8rUaIKmXCLIjKKWCSYoBnpdKob32CRrs6Sk71JQW17K5w9IIYYDZOLrKoel4NQ2kvYCusPUG6m5glC/D+g8gG0fw3WzN2n28KlP40nVIvPaPTJHLmdUwpn4IS91vZTRRXBb9xf6tNvDpaNK5q2gF4FK1JKR54EodLaNEzW7F3pTm1fhphjrJMbkdnmPjHZS7IZAWZyv6FjDv4lnDTdNdDE8Dwqx1C0lL3nufhq89TW787E3PodyqDF1KOwBnTmiakPG68c3s2Ukbgva/PnPi4TFS7UpLYSjpO+gXAt/4XQcdBrKYtLbi9yrg4xn8bMDyzkoqdDE54BGhpeXugsflea3oBvIL9u2gse479ezejd8qWAM7idWxI6qy0/C2cG3g==
  template:
    metadata:
      name: gitea-writeback
      namespace: argocd
    type: Opaque
