---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-writeback
  namespace: argocd
spec:
  encryptedData:
    password: AgDCtpgiAOd/YbkgC0halp874cJ4m6S9OGVuWbIZbEuhekbDiU5OG+KDCLR+Z912nfTfkIkVoYoXcxYqp9ez47HP3LjX0Bc0npBw4TuCtV60fTBZkqRcWM5RxRiy+EELCr4ZllJFGZv0D1Cz3jeBoVBNF+Q41nojwmhYZokczuSETZEbM79Y0PUjo7pq1uFtrxiZMpqGKKu6WuhBvFg3OddN12ckoYPLhxeV/SBm0aG0ss7RvQRTChutuiYd7G1osy2XUVkbZiJwmU0puGFpWgsodwLmVwog84iwncV7lZUSBMd5MPZQGjLVSS+fcL7yOnNjwate36IHlkTLRsVYlO/H1FaOZjcm5JP/Fi+SmWCPiHMlySpDKZ/en5zAkXs7PJ9Pt/9xVuNOGFo/fx4UyoF426YXee9f+Pvun5ZFZQCrYpfczxz8CzCb6MLgShjxAkbNFWqJrZEoxer0Ke4768H6qm6rrKLXOk1nbjHh3txzTBkZ1xKKpZdJw9Wgw595psVxBtr3zBQuHEPAhXQePRVuqk92Keg4mVjNVrHNgFLHDdpytsJuGTwK4aPA/Mq5FZKpR/Vu/tD5IqHJ0CtEQFPhaDwNZqVaQHlljznzNalO2Lmy88ePHvFLArIjPKNNu3grMpq94v/zzdxvvvlMHNeKVdwbGYs2wGN9KqmbXwuhQ3qj/Fl7gZbLqHWMbffEXwNlGHIZlQ0VerT4HeuL7yqUr0XJ8sh9e/A1Ft9BZtuKjLFXwSTwnM2L
    username: AgC/sPQqRo/mvbnydj+1eRklXiYE8VwdeChRgUag6WkwH0QsziMnhUxzO7xcQSfV//TIOJ8A1MashkBAr1cSl65ss6tD8RC3jOkufKHt7YkBTm9H/L5h9uxgDrqhktvR2IyUkuvgX6E0L+pSij0rt71EhCQ6P+lhwW90Z46sKCLJ4e4cazdj/MVi0Q/EvhZO68A04bLYj7LhDkFvXYIgLI+VWMRVPxYk9jJOpQSnRLVEf6MQx29flPcA9pZLK8+0qDaMMzx/z6SvG+9tBj2rqAKMdLjSwcaX96/1/NY6CRg8EBh4rj6ZF+Vtd0n/bAIxZn1FBY2IpPwN5bYeA0++fher2U9NJouEYks7UwBnvfvqs/5+J0+johZfK+KRuXsUyt1M3qQOuHLUvKP5MHqrgPZHhk+L7nyTTBwZdDCCdPxJCiK2c2sr6dqFelkYKx5b7g+gPbrMgCNiPvRodP/SaNeSB/A4qczWuZjsoJdPjcsyI/N2QIXLhQcfROnRbej/ufczB7o7DtUjPT5c/pWixqGF9W7zkRxV5eyJzIgc9IIPHX1dCooF0wtMGtrvf65KQ7Dpmyg91Cz6RZGRnu2GafDBXze6fW0n8rcf3RDfCRU1DOwa0ga1iNcy5ZxSC4e5SlQ9+g2Ms8Nq1m6KXD480ewiLexOUYsEGWgVh1/UM/Fd8VRF4uBDqDaWuZGru+xRZ1+WI5WJYakTAJ/azQ==
  template:
    metadata:
      name: gitea-writeback
      namespace: argocd
    type: Opaque
