---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry-creds
  namespace: argocd
spec:
  encryptedData:
    creds: AgB57Q9nLAuYmd0CUXejwP5jtw97YN6gpp7hLbxEn+NdFlSdQUPpVznO6R597lUfu/HiOuODOcXrGQmdQS7lySq2QkfJjdGnRtKV6opFisTw/xQP9TTPL/EMTMGYVlULfLa9kmgbtjAR3AxhRGrwXn9lQyTnN2TSIsMW1V4WKeTtDuHHpt9CffnBV+YxF7g73x0oOpIFW2dGkaLz/nqf3RhAVmKBWDexpWsH+g3AjapbA8h4JbndkllorJuyjFGiFuC6zqi0yjWKse03l7ijZuoLoNNgbJr6FtVlIAkLng05KPByiVFd4k6xQrjuAkTaC3+IVDbuEuXiYz6HqwWuVPlOKKpja92ug4GNEf/P0tgiCC1tnwccrtvzLdnSX+TDSKRqNtZJHls3dJoIaECSSBFpr4AAe9gD/kEAlvGEIoRvY6chTLb5Xpojop6y9wqu1oxVLA7XX3v2upTgvcTTyu0armEF20SfTHMpc6+BZhX/xtgY7SHRIf68BciSFjipkTQaffg+sTFd8EQW5j4nYfmqdELnh6kYWZ+YIh0OBcvGp3CPuzvZnKWac0JB1XuIqK7btWov8FcZHu/bGTDTJbzn4KHyruBIRnLlqjy8oTCKlGDCBwYQiAXMGXuzuzGR1PxufRqko0CKwnIyaF+msc1x5BmdJbme0UTt3QoSOPxZdCWKdm18jUo7Gnx0O7V6hPOGg0xxLcI8dSy+LwAgQ4+eqcbMfZCXpsJ5wfCvFpyCB7fDmIA+ycQqdV2Hn5MOFRjgpEuh
  template:
    metadata:
      name: gitea-registry-creds
      namespace: argocd
    type: Opaque
