---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-api
  namespace: external-dns
spec:
  encryptedData:
    password: AgBCmKlZ5Ngd0RJ9IAWg4vGCUvq8y4T3pYNk4epJpVPaaKmENFDXz+Yzyp8XvKC+M2cOF/UVIXDEcjtOw0QdBNJUoGMkURNKSnLNUAxXVeNN6wSvlM/ScYt+HfraMMIx6ysp6CWuxvPD62YA6oCCONCMBEIOhR+EHwsFsyd80XkCKbA9NXw+nmABMPI6IlkiOQdkHhBbwmozc3rfQiYKTD42F2kY+7CuxtH2z8uf/mZbzEjDB4X5vLAjnZzw8EuHE5U2qupIHaDHFt3fqnSK9P9Z+u/RQM3Rg2O5ILRZ67C1nqHmG1CTbIc88t+hghwJ3S6nmOp+zGgJEu7bPfEenswCrnsjoMvE9TyUj3RS+JCwlTNd4w7my4IJkATKaA1zlgmE5TwcBY47aY57tYbcxF8IgBQpB15c+h0O048B85+t34icFgnrVVZnFbzKgabMllmeY74MGrSRSFSyyNIDU5BrJ30zKZliCWj2tvsrri7iP8inXXvygHAzndkSOt41ZSQIEJr1W7r8s8CJ2tLAcK/vjbtqKCGwNiILdWcPXKp5E6qY0mGPmAaljN57gwliMRL4qbavuJGfgNiiQ1XNMZlWY/rThJfNIscx8TKTWvqPJTd/YdmrHg3vSzKf40E6W2aD94rmJtS26Ec/x5RI1TBJ1qWLh2Pqikq+CEiWD8LmaLg2HDaseza2tCSX2ztzcoMq44R8CJ8=
  template:
    metadata:
      name: pihole-api
      namespace: external-dns
