---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redop-postgres
  namespace: redop
spec:
  encryptedData:
    DATABASE_URL: AgC3d5qvL2xyc2jpCQoUCnNTyo6EzWqa49e9ehd5GzqYW/4O6a4FDbQcqWCjbbuuMB5uWjlliElnDpdvespVrdI3fzCyfZJKdpLho1pe2/4UqnUSxYcHNblLF4VtqaVuw5dV+B5X8kzyEaYhoFGQkCduF+IJZZTqjTB7e5J6EzJmuTC2guX+T+vV98p4Bzhf33vh7D7ubLQ+hc9QFuAIQVG3e3MFX76LdAUFuP5H8hSzsgEyTcM7anuvUO5TWlokxk5cRLNRXbA9HoBMyavunIxeYg1S8iBCS4HrPTsDezavBZB/MOAw2xIt1gCGiAbfKdWvR9jdNyWsZq4WeMlHqwqpWirBpem/rqqka1t1sMmb+/0LlL5YzBO+ClVIkWxRaJIWtCQV91SZUY+oZ5Hm/m645K+LTvmsfrqjTTwe9wbeMW5U1F9OnqYlq11uXue4VVV7ljXOTMnp/liqBS9ZTlusnkwwtg0crrYpCA/BphI+hw75NdKqOCbu8/PCS5ql+xgfJB0n9QUS1/QL3a0Af/8HbhxHifOuGLKlHNi6DoyhXzRNO26t6WW9q2gKVfMpI+Qr9nrhmQ5CTeH5Wk2IgF8TPZIE5sGwnbv/hqzTc7d8qsCx6Ps3auU3hZMpDcWqgyTi3INup9MokDeD8QX+3d+lyOIBTuAeTQ2nhBrhIZC6mtc5Sg99yZeYLeX7xWCbFj8I/Ws2ftULL5aPkSkLmZjkyVsJEuugC9m9hSBA1ItS7HFKX0T4HyA5US8ZZqcrDxzgKoNVRXSbbeWQlqKpmVLEOyHHU7k3qT6HAAchG3xQ
    POSTGRES_PASSWORD: AgCFzrOZqynF9oL2/CUQ8eZd9hmkLdI1Ub0nbRhWe/l4iyV/AdPwGPGYPx1fNvbtR3ZOvjjpW9VvI7I7LxrQJLIYcd++PiIMuBWqOAjBHoPOyhkUOX7OXtd6Z+3ObO6HW0HsDHX84gDnRnt3ZaWFm3FbAV+dFjyBHJlZtYTLqt0/cvRsDAhTW9nTgM7lE5CfdysgUGkSJ/Z8FH10K40ggIeOSlLbpYLbHWOKI/neTLvVElIGyycihI0Ot5JuJYR4p5xo03YFOzVd3auZDlPe2BTAvD4J5ZVmZnSBT7t9JXYkBkR5l68T4tPgZFwkXQftk3MVfa28Iw+WKN5CsBPCEDq6EAGCi4w7pEmBKnYd75fwPNIwAQWMXf2iTjc22cBfz/0XqX0f8zaZlfeE0r0Xwh8JL8isEI6u3QciDR4yUW6ycB7RM9ZolnC3mFUel/WyQDbR6a/MVIU7RHp0zT0AwZRXo59PvfNCJ0OqUY8Yx08eyEvfTr1HkKhMjEcUR8OHDr+SbiOKsxV7bDwqIBaUDqWpcwZb5VrTW4ygBvWQFJYoYpzLy1fKArxhRBhwfzgDGReu1zKsy7pZuGeO08ws/JW8M5fSfuh+NfuFMKH6LfcV8r1FwZc+iq0oDcWF4Y/xYK4Q7+lfqQ9lsNGZOjX2zj4y9cUABoxHFiyaTa5VyFpHEHLHSU9DXk0uQw/gf4DjYOpPugDK+32FGaYpW3YB2QC0BsUgkVBX6f4o2yWF2XZabw==
  template:
    metadata:
      name: redop-postgres
      namespace: redop
    type: Opaque
