---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redop-postgres
  namespace: redop
spec:
  encryptedData:
    DATABASE_URL: AgAQAbMsbTvtJmyMb+PPeMReefrC0CRQZdv1eBH0E/PGt28vIhi6kiM8JMN8wCZESD5STn1U2iMzv8O5dtW4F77tPp2HIR5JYHsgsNgb0QGAZpr81Q1fthIoqDYMkUXsshJrSvfKISN/feyD27y0daanwQh3X0i0ZQoh6NosnOG2BuzdupgTJFl6lKbQuwMn8EWdfbOS7vE5L8Cgkjs2izP3e8kNSkpec5R+9aB1sqE2nTmPrZDN75z3a3GRmxmqEGVQmZyKcKoOjfzs1SQ0ki7Lbz0SjdlzGfCZhTtewWeGDUyS2MpXCwYRpXgn6tAsTxzsKR5UETMXWZVBuRjdMfeTteeSpj+3ZCHBGHOooyq1IrpufBZpuv//X0AESnAVDnbIlIiVN2t8sQkmhZa0DAq9zcBep9zfijtsveDfvv/enyT5Ax07dJuBI0VQs3CH5k/XXoFxHt4sOABNuPvIwEDh9fhq1j7aKS52uDwsjiuotE0BRT0AaIygIavQvRMJm6YodHjCyNFEowI3qOD8LkFlC8nmOY82rVGD9/Y/jCU6nzp+l4tIdlpgtM0U81vASNEYcCDYuYccE7qruTmrdq/MRX9cQtCLpqiMCzB6e0E5cdZi/Fc49nrGV8/+JhOR+6/lnnQG3ZlL2DCFAf01RTWhBbbkfcspveepY1fxK6rnoKFijpV0/TnssLpAOC2UqYwQhyTpty0rsUKTOdfv1xrRxzopryMEjF8Xqlfq9qGWvbMatrsIZ+r50osshHGwcutbeZUw4r7PuBVkH1RolJI3vs9RU/3nl9ynuw8v8WNX3L8GupPJBxTzn//fn1Mg1g==
    POSTGRES_PASSWORD: AgCo2RCVLuOYeZ6sjP/05Ascx+09n7mqsJdy4xX+pxSoqrENgF+Gk++2STOsAR0al91OGbURSO06nos9Sq8FE+t0AS/iMAx27WepuljNazum9LunvK+K55rMblgr00sTNWGDsSS3IuwpR3H7M2NNNt2M8M+Eo6j/23J1/vVrssJgP5X4nKRfRzSJzGtmpVQffP77O1RilCNiua/0KEwJ4NrFTbPpMMiBvk5smBC7rNtOhZnKkPLiT6g7dG9+IgJ6LpXRG+ue6Aov8J3G+eIvobBF9pjZnj7wqqRjT+Mb5SRJ5yPMLoo4JpYh2hlmCEGD3mCcfY4NjmOfn8+cFbEbGIi5rL24koPPqdRDd/9HYuQSWxYjmIGb7bCpEl3BYwm3cGqg0PVb2EKQyCKATUbQ8CkV5bjvP1gkUHYBih5y8q4H3Fp6fcm45WTC/TBMSkukdYTCRefkOp18bgeNgiqwW9B/aq6ua/lgWU6ri4Oiu8yPn4SGYaZuvIu6Yr9y83spU+iwmL9QdaxIJFKD03UtveZ+/jB3hMiOHU4d5MgZdGw4e669nG8ccA1UXmNFysVNivxRy/qou0cwjgnUtqBPxqx+/DexY9atru0163yQnR7Ya1M87vgh/aY+++AjxhUWZ0vt1pqkmy848lklEVYpiUU/+IOdikjl4kWaXaWV35c9cM94K1YgeSkLscJQfO2mQg4kEt/AdsF3dYa2Dio7H8km2eswVSrhDp9zl97RZIZX0n7oO01R43kX4/Df11ZrFCQ=
  template:
    metadata:
      name: redop-postgres
      namespace: redop
    type: Opaque
