apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odysseus
  annotations:
    cert-manager.io/cluster-issuer: atlas-ca
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Odysseus
    gethomepage.dev/group: Apps
    gethomepage.dev/description: Odysseus application
spec:
  ingressClassName: traefik
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odysseus
                port: { number: 7000 }
