---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: odysseus-admin-credentials
  namespace: odysseus
spec:
  encryptedData:
    password: AgA0tO4cZoaTQ9qGFrUhqEzgurukp1qnwYOVGQSjkSahNIeeKD40Rt0oLdWldoQVAyWv1sCazPZxLxq1kPBPIBNBuHkzZ6NLJBndG+tniEsFNUAzsAQkJdVdyf08nJbxWKKuAcVSNmOwhosOThEgkkoQauQcis40Kyy9ufQ7OQU9PaHkSw/piwTDYqBvrRvxEjKbYeC9HtL7pYFjdObWFG4vGdmcOa4JxRUhYRzzgkTmKlMyVTW/kO9Qx38hEknE583CNonrOjgld7BIwPgUdy8JVrI6fSKPRl8EupKDMAtnlmY7ROIjGfj4Mxiq6XrxbI4o/yv8q0xRS6R0Cdg1ZWDrNd2uYYBNZqqXq7L5vTzi5Rx+crjtURKto0/8XrmF+x19S9heDjaL6etYcCgmuQQ4omHcLNpojP38xrkQMEZs7fYY0VjMyZc5HLaJjeziii7XnWlmVeqypwsgB3ZTyQyUexqRkZ/7+8cOAOID/k7JToQSqbmm6JC3KDjeF3Tu8RNqStrtmMHbeW+pSZ49hCqy49kQXeWdSOCgvWM+MNM+eUh64nk2gdGdwFBHO4QuwnDswoLELzx3S+vzJQWRs2bhMKfx0NNs7F2tKTZMgv20cBDcHfM38EGxuqfS6Ts7vGRwkdWKjn+HLlt2+PEybCZsnXv1/J7Jv+Nd38/WOdBgrakUVS0Zp1BhHgMZZvW6TM5Vg6WTyltWxZgwoFYjh4bC4NY8ve9GoFUjFPhE1nPKpQ==
    username: AgAfTHtyX6tG/4Pm0/kobbkOpLFByQ9UJwrO2ICoLMb58quW9bQ42iZj+dTxz4bG1PKSv3gM/qgkL8otk7yrcVgjlUy5JUMxGIt8wXBT+pk7qcO+l+A60CEULmKo6W1Yt9L0RQViMHRl4jzhRTGKRff+keDBSPYq+1nCWU075mr2W9DHs2BAaLJRYQYigeCfd5pj4xoUhzWrTkSng/3ohb5zcexYzs+dSah5u0DV9a+z2JiEv5rn8hkF6TFUXmj4O+Oh0lMbaXyy0c1lSK3hpHDIyMTh44oono1aMvWNR05rI8uSfqIR9iWxF3xquWYDSo8OAAo/bjQr1Htmkesnr2gBOuieOJ8vcRj3Wc9Nc1SHwu/Pree6w1eN4PDS/8OiVsMA/8fbJqMPDJPGhtTEU7MRuN/KXR3BaRLqqPP4VXP+i15VEKuFtq/VekgCWB/VaoqFv1gCOnTNW2Zp1X8GFCvRzcJOuZiEIswnuy4Q+qb7moZ/so8Z6VixkvLVbZ3Z7T6GGhfNl9MPf8wNJ1esHOm09Y4i9JUUj7Rfn2qghUBbfN9hIp6QB8UQTPeYJ/Xh4ywW+ZwQQjDn9UsqcYNM7YCGxSZJXdx5CJz/1eZEpDCocUhihAn/NHJ1CwgfEMILi5o/eJTosLrO2tgqlDnET87rbxk0Hrpj+vrxu7qhMmAUVpdORscEvW2XmfnfXgea95H2iTGoFA==
  template:
    metadata:
      name: odysseus-admin-credentials
      namespace: odysseus
