apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3f-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: 3f-app
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/atlas-admin/atlas.git
    targetRevision: main
    path: apps/3f-app/chart
    helm:
      releaseName: 3f-app
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
