apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dave-study
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: dave-study
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/atlas-admin/atlas.git
    targetRevision: main
    path: apps/dave-study/chart
    helm:
      releaseName: dave-study
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
