---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atlas-landing-secrets
  namespace: atlas-landing
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgBenQgVAy2iUUeClQfHlbhJMG24rVhyvpLPSHudKxTeQ0LEwhBjrZtEE9cXGxsXU7vv6dC+iBpCjP0hCM/c3mTIUO9u3Wz7w6IqV1FVIzv4gXIe9O0bgosUMhtzXBcyrJDmV0EuHfKVcMbrCFnRfipoOTxN//MIK9/+CWrOfsq4hthjBG+K4+alavV1NbRWYaqstSnij/2dCkWNUTlxnqZQK7q3Uk3ZB3W1qqQLUSwHcofC2AJFfzd7JnpzsXGeyLkA3MY39JYu03b6sMnMkO4eBw1dBe93FZPd3CyQ5NJTkt2N09Dqpx+5ING0ROfFwqSOQWOmsjn+lATIXKAShWpBgR7OJIllDF7DMtreqIVEc3x+uPmoChYbD+XqFI75d6Nfg0IpmdT2IjxdCIM379pIiO+BcoKR6J7YagZFKCfTXEGHR1wujxTanhRCyOF5EskrqXykqrMOo5aa8YzSGJghZoOLwDJzHRGCbEsuCXJgpgmVcInpYlRCISUoquX8IxbtQC5TAVo9qQSJ4FqzBWLiDfSlGn/D92YoDm+6v7xoXWYIeDKFU3CKJAHH3QPRHzZSOBA/GjctuW7aQ2v7PLhjU2fY7AS1p7+IH3D88U4hs3nrnIdx4KsqrQtZOpS8j5+03qX11gfukR/Qp1pKjyea6oXT2uGFjsQU3SZmchZRmDhBHxvQsAqUEf/UtjqNr8W7FwJAzCN3HPxaHcmIAtyYv24psYVi5IsO8brH/LeArNiLFH3T3M3Ew45KRMPo73vYOLlmvQ0nfawCNlX41t/LzBpL5RHUg3yh
  template:
    metadata:
      name: atlas-landing-secrets
      namespace: atlas-landing
    type: Opaque
