apiVersion: v1
kind: Service
metadata:
  name: atlas-landing
  labels:
    app.kubernetes.io/name: atlas-landing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atlas-landing
  ports:
    - name: http
      port: {{ .Values.service.homepagePort }}
      targetPort: http
      protocol: TCP
    - name: background
      port: {{ .Values.service.backgroundPort }}
      targetPort: background
      protocol: TCP
