apiVersion: v1
kind: Service
metadata:
  name: redop-postgres
spec:
  selector:
    app: redop-postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
