apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    RESTIC_PASSWORD: AgDEoaSAO/11FCS8WZDBG7C7W3L+RCt89tO1KD7DQEWXxVNuqJpOeiYIW4RTx4fJ+GIkll3wRL+RTKwRk/DEUtWLu1YCx3fiZha8quaLazAPU/rdWrKgFZ9BKneqJ74vv10c99L44oIKyuMJaWiAGjP++koM4klMrv0XUIiUIPNd44QStTjlFqQlOjN0uBnJXAzx6PcrX636J1E9n/cX0Vi5IxPhmxz+3i+dzEeO85nm877tWpD6780suZPYt82b4Z8ryr9oeQh6ar6zCRaa7w8kqYtZUT38mVhuKNgr2eRD5muqnBnVML8pRUWRODs/cw4d2xAQkpQkXOJP21RzEn+9vNr2CEfRDMnGJQv35D09EFeIHvbcbIer8rtlUIJjCaIUMST/s00N1+dbyUvDeTtkUjb6IZUJr5iCPyWP7iIRWUQU344d277wgsxNDAL1cU9YIsZF48nuayU7sQOBh14MT5eYwfS1bSf3bkpxDetW6K2aCR+QXvcqPXCySKz98H7xA0B0FPYuiSPFFg7sbptybCSu7V4dSwA7dQcwyXtOOEjcT176A3goY7z+e1RiJrgu6OI8166LSD83+pA8ODDo7eW0c8yh3IE8sOA30lSI9t/Wu/MO+d7AaQa+rbw+SSfOJOm1F3RemmPu+ZguChJKN8rA51GtG4mNSDVjR9gqb7WYNNl5dMBq/LlD75r+2goN6SpXrjtmgAZUyWqtKgkxruggt5nsIlWRTxPu8+EWyfdCQP7iTCAarsvQdAlEHZnNJgt6Y5NEAv0Pah74HNG9
  template:
    metadata:
      name: immich-secrets
      namespace: immich
