apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: docs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    .dockerconfigjson: AgAZx1p+6DAdRvJaRfTkAtPssbVGiDyyqFc7r7tvc0KkOa6IbCsN6bWZsy2wn3NXzrvy3ukfxAXstYaVnYKMPS+kc/LW8KFo64872pIi6GFnPoqjjUVG3M/lsUJ0W/Xyv07ZSjbG4xFSnWkvE2zr+dFygkTmz0bYPWMjMQZ1F3MjFDj+KPCanLk0GQw/7ljJt8gTJ2USA5XzE0hzdRBeYUSkUVgpaaMB6c7/upPskE1rHop8VN+1nxOOl4qBWr5ucSHXTf2EMj6Wdm+xhW9cPRvR6dUpXpuXfBtdq4386NDYuqCMiHQv/chTH7MdBhBLI+qof9t9PKV9+jKSjytOKLG322lQOA8xa8ojDzID55GIdHdEFDIRYtRYuEtiwtVPkO/qARQZg3A7xDEN5aAzCSTWMijOY+yrN5qCNdvtHK2Jb44ru//DwwRJlfjVg0y2pt1Up/eieEwCJovlgW6gNkERzMeXtW6db4ZLqRuN8ZSdzapuYZX8ukipdwDzRItqD9j0bLhY8c4nM3RVcLfINgdYKINMUjs5cBG5kwtDOH8ObS4wB8DF7FmFhc9yzL9UiAS/oL0ZhSnEhMgntyLzcGCLZU6MxUgM58OYhxMXn3b4NvjBkoFyeQXuTwFOdfiS45mqAcB72smPUYI5oUD8lJoin4B1LlLtikZIqhm8HFF3HrL3XF1MYpE4rIsyhJ3kCfTyO+9CgcC7c/2p29hiBkHwl9LvX7tukoTCHeknBZzVku8pgcFa08TbaO/KzsmxjEoNnHxFaqpqEJpnGWj/9HeuWmIuK8M9D9KKYjVwPH4+RrNkKCSkkbqx2xuBafwDOGGVV9ipfYomNQdRAfNz55XFGup8oMZyNHpBSBlJl75IU2IUgHNA2MwjNk0tBBYriQHefDOmrGQ3pbzJKfhHhHqAEgHLXZz5T/ZSSMRxMeAbWGer1nQjG4RoSBIXtjyfH6nVxeG64GIL58Q1
  template:
    metadata:
      name: gitea-registry
      namespace: docs
    type: kubernetes.io/dockerconfigjson
